// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cloudproviderics.proto

package cloudproviderics

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node struct {
	Vcenter              string   `protobuf:"bytes,1,opt,name=vcenter,proto3" json:"vcenter,omitempty"`
	Datacenter           string   `protobuf:"bytes,2,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Dnsnames             []string `protobuf:"bytes,4,rep,name=dnsnames,proto3" json:"dnsnames,omitempty"`
	Addresses            []string `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Uuid                 string   `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_630e23fe7cf01247, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetVcenter() string {
	if m != nil {
		return m.Vcenter
	}
	return ""
}

func (m *Node) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetDnsnames() []string {
	if m != nil {
		return m.Dnsnames
	}
	return nil
}

func (m *Node) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Node) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetNodeRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeRequest) Reset()         { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()    {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_630e23fe7cf01247, []int{1}
}

func (m *GetNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRequest.Unmarshal(m, b)
}
func (m *GetNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRequest.Merge(m, src)
}
func (m *GetNodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeRequest.Size(m)
}
func (m *GetNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRequest proto.InternalMessageInfo

func (m *GetNodeRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetNodeReply struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeReply) Reset()         { *m = GetNodeReply{} }
func (m *GetNodeReply) String() string { return proto.CompactTextString(m) }
func (*GetNodeReply) ProtoMessage()    {}
func (*GetNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_630e23fe7cf01247, []int{2}
}

func (m *GetNodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeReply.Unmarshal(m, b)
}
func (m *GetNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeReply.Marshal(b, m, deterministic)
}
func (m *GetNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeReply.Merge(m, src)
}
func (m *GetNodeReply) XXX_Size() int {
	return xxx_messageInfo_GetNodeReply.Size(m)
}
func (m *GetNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeReply proto.InternalMessageInfo

func (m *GetNodeReply) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *GetNodeReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ListNodesRequest struct {
	Vcenter              string   `protobuf:"bytes,1,opt,name=vcenter,proto3" json:"vcenter,omitempty"`
	Datacenter           string   `protobuf:"bytes,2,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNodesRequest) Reset()         { *m = ListNodesRequest{} }
func (m *ListNodesRequest) String() string { return proto.CompactTextString(m) }
func (*ListNodesRequest) ProtoMessage()    {}
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_630e23fe7cf01247, []int{3}
}

func (m *ListNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesRequest.Unmarshal(m, b)
}
func (m *ListNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesRequest.Marshal(b, m, deterministic)
}
func (m *ListNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesRequest.Merge(m, src)
}
func (m *ListNodesRequest) XXX_Size() int {
	return xxx_messageInfo_ListNodesRequest.Size(m)
}
func (m *ListNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesRequest proto.InternalMessageInfo

func (m *ListNodesRequest) GetVcenter() string {
	if m != nil {
		return m.Vcenter
	}
	return ""
}

func (m *ListNodesRequest) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

type ListNodesReply struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNodesReply) Reset()         { *m = ListNodesReply{} }
func (m *ListNodesReply) String() string { return proto.CompactTextString(m) }
func (*ListNodesReply) ProtoMessage()    {}
func (*ListNodesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_630e23fe7cf01247, []int{4}
}

func (m *ListNodesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesReply.Unmarshal(m, b)
}
func (m *ListNodesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesReply.Marshal(b, m, deterministic)
}
func (m *ListNodesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesReply.Merge(m, src)
}
func (m *ListNodesReply) XXX_Size() int {
	return xxx_messageInfo_ListNodesReply.Size(m)
}
func (m *ListNodesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesReply proto.InternalMessageInfo

func (m *ListNodesReply) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ListNodesReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_630e23fe7cf01247, []int{5}
}

func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

type VersionReply struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionReply) Reset()         { *m = VersionReply{} }
func (m *VersionReply) String() string { return proto.CompactTextString(m) }
func (*VersionReply) ProtoMessage()    {}
func (*VersionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_630e23fe7cf01247, []int{6}
}

func (m *VersionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionReply.Unmarshal(m, b)
}
func (m *VersionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionReply.Marshal(b, m, deterministic)
}
func (m *VersionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionReply.Merge(m, src)
}
func (m *VersionReply) XXX_Size() int {
	return xxx_messageInfo_VersionReply.Size(m)
}
func (m *VersionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionReply.DiscardUnknown(m)
}

var xxx_messageInfo_VersionReply proto.InternalMessageInfo

func (m *VersionReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*Node)(nil), "cloudproviderics.Node")
	proto.RegisterType((*GetNodeRequest)(nil), "cloudproviderics.GetNodeRequest")
	proto.RegisterType((*GetNodeReply)(nil), "cloudproviderics.GetNodeReply")
	proto.RegisterType((*ListNodesRequest)(nil), "cloudproviderics.ListNodesRequest")
	proto.RegisterType((*ListNodesReply)(nil), "cloudproviderics.ListNodesReply")
	proto.RegisterType((*VersionRequest)(nil), "cloudproviderics.VersionRequest")
	proto.RegisterType((*VersionReply)(nil), "cloudproviderics.VersionReply")
}

func init() { proto.RegisterFile("cloudproviderics.proto", fileDescriptor_630e23fe7cf01247) }

var fileDescriptor_630e23fe7cf01247 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6a, 0xc2, 0x40,
	0x10, 0x86, 0x8d, 0x46, 0x6d, 0xa6, 0x22, 0x61, 0x29, 0x12, 0x44, 0x24, 0x2c, 0x3d, 0x48, 0x29,
	0x39, 0xd8, 0x37, 0xb0, 0x07, 0x29, 0xd8, 0x12, 0x6c, 0xe9, 0x3d, 0xcd, 0xee, 0x61, 0x41, 0xb3,
	0xe9, 0x4e, 0x22, 0xf8, 0x06, 0x7d, 0x8e, 0x3e, 0x69, 0xd9, 0x4d, 0x4c, 0xa3, 0xb1, 0x1e, 0x7a,
	0xdb, 0x99, 0xf9, 0x98, 0xff, 0x9f, 0x3f, 0x04, 0x46, 0xf1, 0x46, 0xe6, 0x2c, 0x55, 0x72, 0x27,
	0x18, 0x57, 0x22, 0xc6, 0x20, 0x55, 0x32, 0x93, 0xc4, 0x3d, 0xed, 0xd3, 0x6f, 0x0b, 0xec, 0x17,
	0xc9, 0x38, 0xf1, 0xa0, 0xbf, 0x8b, 0x79, 0x92, 0x71, 0xe5, 0x59, 0xbe, 0x35, 0x73, 0xd6, 0x87,
	0x92, 0x4c, 0x01, 0x58, 0x94, 0x45, 0xe5, 0xb0, 0x6d, 0x86, 0xb5, 0x0e, 0x21, 0x60, 0x27, 0xd1,
	0x96, 0x7b, 0x1d, 0x33, 0x31, 0x6f, 0x32, 0x86, 0x2b, 0x96, 0xa0, 0x7e, 0xa2, 0x67, 0xfb, 0x9d,
	0x99, 0xb3, 0xae, 0x6a, 0x32, 0x01, 0x27, 0x62, 0x4c, 0x71, 0x44, 0x8e, 0x5e, 0xd7, 0x0c, 0x7f,
	0x1b, 0x7a, 0x5b, 0x9e, 0x0b, 0xe6, 0xf5, 0x8a, 0x6d, 0xfa, 0x4d, 0x6f, 0x61, 0xb8, 0xe4, 0x99,
	0xb6, 0xb9, 0xe6, 0x9f, 0x39, 0xc7, 0xac, 0xa2, 0xac, 0x1a, 0x15, 0xc2, 0xa0, 0xa2, 0xd2, 0xcd,
	0x9e, 0xdc, 0x81, 0x9d, 0x48, 0xc6, 0x0d, 0x73, 0x3d, 0x1f, 0x05, 0x8d, 0x4c, 0x0c, 0x6a, 0x18,
	0x72, 0x03, 0x5d, 0xae, 0x94, 0x3c, 0x9c, 0x57, 0x14, 0x74, 0x05, 0xee, 0x4a, 0xa0, 0x59, 0x89,
	0x07, 0xe5, 0x7f, 0xe7, 0x44, 0xdf, 0x60, 0x58, 0xdb, 0xa6, 0x1d, 0xde, 0x43, 0x57, 0xab, 0xa3,
	0x67, 0xf9, 0x9d, 0x0b, 0x16, 0x0b, 0xe8, 0x0f, 0x8f, 0x2e, 0x0c, 0xdf, 0xb9, 0x42, 0x21, 0x93,
	0xd2, 0x21, 0x9d, 0xc1, 0xa0, 0xea, 0x68, 0x15, 0xed, 0xb8, 0xa8, 0x2b, 0xc7, 0x45, 0x39, 0xff,
	0x6a, 0x83, 0xfb, 0xa8, 0x25, 0xc3, 0x52, 0xf2, 0x29, 0x46, 0xf2, 0x0c, 0xfd, 0x32, 0x46, 0xe2,
	0x37, 0x0d, 0x1d, 0x7f, 0x87, 0xf1, 0xf4, 0x02, 0x91, 0x6e, 0xf6, 0xb4, 0x45, 0x5e, 0xc1, 0xa9,
	0xae, 0x26, 0xb4, 0x89, 0x9f, 0x06, 0x3c, 0xf6, 0x2f, 0x32, 0xc5, 0xd2, 0x10, 0x60, 0xc9, 0xb3,
	0xf2, 0xca, 0x73, 0x36, 0x8f, 0x23, 0x39, 0x67, 0xb3, 0x1e, 0x11, 0x6d, 0x2d, 0xe6, 0x30, 0x89,
	0xe5, 0x36, 0x10, 0x09, 0xa6, 0xb9, 0x3a, 0xa6, 0x03, 0x11, 0xe3, 0xa2, 0x91, 0x53, 0x68, 0x7d,
	0xf4, 0xcc, 0x4f, 0xf5, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff, 0x82, 0x31, 0xa0, 0x2b, 0x6e, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CloudProviderIcsClient is the client API for CloudProviderIcs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CloudProviderIcsClient interface {
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesReply, error)
	GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionReply, error)
}

type cloudProviderIcsClient struct {
	cc *grpc.ClientConn
}

func NewCloudProviderIcsClient(cc *grpc.ClientConn) CloudProviderIcsClient {
	return &cloudProviderIcsClient{cc}
}

func (c *cloudProviderIcsClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error) {
	out := new(GetNodeReply)
	err := c.cc.Invoke(ctx, "/cloudproviderics.CloudProviderIcs/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudProviderIcsClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesReply, error) {
	out := new(ListNodesReply)
	err := c.cc.Invoke(ctx, "/cloudproviderics.CloudProviderIcs/ListNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudProviderIcsClient) GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionReply, error) {
	out := new(VersionReply)
	err := c.cc.Invoke(ctx, "/cloudproviderics.CloudProviderIcs/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudProviderIcsServer is the server API for CloudProviderIcs service.
type CloudProviderIcsServer interface {
	GetNode(context.Context, *GetNodeRequest) (*GetNodeReply, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesReply, error)
	GetVersion(context.Context, *VersionRequest) (*VersionReply, error)
}

// UnimplementedCloudProviderIcsServer can be embedded to have forward compatible implementations.
type UnimplementedCloudProviderIcsServer struct {
}

func (*UnimplementedCloudProviderIcsServer) GetNode(ctx context.Context, req *GetNodeRequest) (*GetNodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (*UnimplementedCloudProviderIcsServer) ListNodes(ctx context.Context, req *ListNodesRequest) (*ListNodesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (*UnimplementedCloudProviderIcsServer) GetVersion(ctx context.Context, req *VersionRequest) (*VersionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}

func RegisterCloudProviderIcsServer(s *grpc.Server, srv CloudProviderIcsServer) {
	s.RegisterService(&_CloudProviderIcs_serviceDesc, srv)
}

func _CloudProviderIcs_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudProviderIcsServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudproviderics.CloudProviderIcs/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudProviderIcsServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudProviderIcs_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudProviderIcsServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudproviderics.CloudProviderIcs/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudProviderIcsServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudProviderIcs_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudProviderIcsServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudproviderics.CloudProviderIcs/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudProviderIcsServer).GetVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CloudProviderIcs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloudproviderics.CloudProviderIcs",
	HandlerType: (*CloudProviderIcsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNode",
			Handler:    _CloudProviderIcs_GetNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _CloudProviderIcs_ListNodes_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _CloudProviderIcs_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloudproviderics.proto",
}
